-- Drop and recreate user_fed_lrsj with adjusted schema
DROP TABLE IF EXISTS public.user_fed_lrsj;

CREATE TABLE public.user_fed_lrsj (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_membro TEXT,
  nome_completo TEXT,
  nome_patch TEXT,
  genero TEXT,
  data_nascimento DATE,
  idade INT,
  nacionalidade TEXT,
  email TEXT,
  telefone TEXT,
  cidade TEXT,
  estado TEXT,
  endereco_residencia TEXT,
  graduacao TEXT,
  dan INT,
  nivel_arbitragem TEXT,
  academia_id UUID,
  status_membro TEXT,
  data_adesao DATE,
  plano_tipo TEXT,
  status_plano TEXT,
  data_expiracao DATE,
  url_foto TEXT,
  url_documento_id TEXT,
  url_certificado_dan TEXT,
  tamanho_patch TEXT,
  lote_id TEXT,
  observacoes TEXT
);
