-- Supabase table schema for user_fed_lrsj (athletes import)
CREATE TABLE public.user_fed_lrsj (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_completo VARCHAR(255) NOT NULL,
  cpf VARCHAR(14),
  data_nascimento DATE NOT NULL,
  genero VARCHAR(20) NOT NULL,
  graduacao VARCHAR(50) NOT NULL,
  academia_sigla VARCHAR(20),
  rg VARCHAR(20),
  email VARCHAR(100),
  celular VARCHAR(20),
  instagram VARCHAR(50),
  cidade VARCHAR(50),
  estado VARCHAR(2),
  dan_nivel VARCHAR(20),
  data_graduacao DATE,
  nivel_arbitragem VARCHAR(50),
  observacoes TEXT
);

-- Index for CPF (optional, not unique)
CREATE INDEX IF NOT EXISTS idx_user_fed_lrsj_cpf ON public.user_fed_lrsj (cpf);
