-- Tabela de referência central de graduações (kyu/dan)
-- Fonte dos valores: planilha kyudan.csv
-- Objetivo: ser a referência oficial para graduações no sistema

CREATE TABLE IF NOT EXISTS public.kyu_dan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cor_faixa TEXT NOT NULL,
  kyu_dan TEXT NOT NULL UNIQUE,
  icones TEXT,
  ordem SMALLINT NOT NULL UNIQUE,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_kyu_dan_cor_faixa ON public.kyu_dan (cor_faixa);
CREATE INDEX IF NOT EXISTS idx_kyu_dan_ordem ON public.kyu_dan (ordem);

CREATE OR REPLACE FUNCTION public.set_kyu_dan_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_kyu_dan_updated_at ON public.kyu_dan;

CREATE TRIGGER trg_kyu_dan_updated_at
BEFORE UPDATE ON public.kyu_dan
FOR EACH ROW
EXECUTE FUNCTION public.set_kyu_dan_updated_at();

INSERT INTO public.kyu_dan (cor_faixa, kyu_dan, icones, ordem)
VALUES
  ('Branca', 'mūkyū', '⚪️⚪️', 1),
  ('Branca e Cinza', '11º kyū', '⚪️⬜', 2),
  ('Cinza', '10º kyū', '⬜⬜', 3),
  ('Cinza e Azul', '9º kyū', '⬜🟦', 4),
  ('Azul', '8º kyū', '🟦🟦', 5),
  ('Azul e Amarela', '7º kyū', '🟦🟨', 6),
  ('Amarela', '6º kyū', '🟨🟨', 7),
  ('Amarela e Laranja', '5º kyū', '🟨🟧', 8),
  ('Laranja', '4º kyū', '🟧🟧', 9),
  ('Verde', '3º kyū', '🟩🟩', 10),
  ('Roxa', '2º kyū', '🟪🟪', 11),
  ('Marrom', '1º kyū', '🟫🟫', 12),
  ('Preta', '1º dan', '⬛⬛', 13),
  ('Preta', '2º dan', '⬛⬛', 14),
  ('Preta', '3º dan', '⬛⬛', 15),
  ('Preta', '4º dan', '⬛⬛', 16),
  ('Preta', '5º dan', '⬛⬛', 17),
  ('Vermelha e Branca', '6º dan', '🟥⬜', 18),
  ('Vermelha e Branca', '7º dan', '🟥⬜', 19),
  ('Vermelha e Branca', '8º dan', '🟥⬜', 20),
  ('Vermelha', '9º dan', '🟥🟥', 21),
  ('Vermelha', '10º dan', '🟥🟥', 22)
ON CONFLICT (kyu_dan) DO UPDATE
SET
  cor_faixa = EXCLUDED.cor_faixa,
  icones = EXCLUDED.icones,
  ordem = EXCLUDED.ordem,
  ativo = TRUE,
  updated_at = NOW();

CREATE OR REPLACE FUNCTION public.map_dan_nivel_to_number(dan_nivel TEXT)
RETURNS INT
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  normalized TEXT;
BEGIN
  IF dan_nivel IS NULL OR trim(dan_nivel) = '' THEN
    RETURN NULL;
  END IF;

  normalized := UPPER(trim(dan_nivel));

  RETURN CASE normalized
    WHEN 'SHODAN' THEN 1
    WHEN 'NIDAN' THEN 2
    WHEN 'SANDAN' THEN 3
    WHEN 'YONDAN' THEN 4
    WHEN 'GODAN' THEN 5
    WHEN 'ROKUDAN' THEN 6
    WHEN 'NANADAN' THEN 7
    WHEN 'HACHIDAN' THEN 8
    WHEN 'KYUDAN' THEN 9
    WHEN 'JUDAN' THEN 10
    ELSE NULL
  END;
END;
$$;

CREATE OR REPLACE FUNCTION public.resolve_kyu_dan_id(
  graduacao_text TEXT,
  dan_numeric INT DEFAULT NULL,
  dan_nivel_text TEXT DEFAULT NULL
)
RETURNS BIGINT
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  resolved_id BIGINT;
  normalized_graduacao TEXT;
  resolved_dan INT;
  dan_from_text INT;
BEGIN
  resolved_dan := COALESCE(dan_numeric, public.map_dan_nivel_to_number(dan_nivel_text));

  IF resolved_dan IS NOT NULL AND resolved_dan BETWEEN 1 AND 10 THEN
    SELECT kd.id
    INTO resolved_id
    FROM public.kyu_dan kd
    WHERE kd.kyu_dan = resolved_dan::TEXT || 'º dan'
    LIMIT 1;

    IF resolved_id IS NOT NULL THEN
      RETURN resolved_id;
    END IF;
  END IF;

  IF graduacao_text IS NULL OR trim(graduacao_text) = '' THEN
    RETURN NULL;
  END IF;

  normalized_graduacao := UPPER(trim(graduacao_text));

  IF normalized_graduacao LIKE '%DAN%' THEN
    dan_from_text := NULLIF(substring(normalized_graduacao FROM '([0-9]{1,2})'), '')::INT;
    IF dan_from_text IS NOT NULL AND dan_from_text BETWEEN 1 AND 10 THEN
      SELECT id INTO resolved_id FROM public.kyu_dan WHERE kyu_dan = dan_from_text::TEXT || 'º dan' LIMIT 1;
    ELSE
      SELECT id INTO resolved_id FROM public.kyu_dan WHERE kyu_dan = '1º dan' LIMIT 1;
    END IF;

    IF resolved_id IS NOT NULL THEN
      RETURN resolved_id;
    END IF;
  END IF;

  IF normalized_graduacao LIKE '%BRANCA E CINZA%' OR normalized_graduacao LIKE '%11%' THEN
    SELECT id INTO resolved_id FROM public.kyu_dan WHERE kyu_dan = '11º kyū' LIMIT 1;
  ELSIF normalized_graduacao LIKE '%CINZA E AZUL%' OR normalized_graduacao LIKE '%9%' THEN
    SELECT id INTO resolved_id FROM public.kyu_dan WHERE kyu_dan = '9º kyū' LIMIT 1;
  ELSIF normalized_graduacao LIKE '%AZUL E AMARELA%' OR normalized_graduacao LIKE '%7%' THEN
    SELECT id INTO resolved_id FROM public.kyu_dan WHERE kyu_dan = '7º kyū' LIMIT 1;
  ELSIF normalized_graduacao LIKE '%AMARELA E LARANJA%' OR normalized_graduacao LIKE '%5%' THEN
    SELECT id INTO resolved_id FROM public.kyu_dan WHERE kyu_dan = '5º kyū' LIMIT 1;
  ELSIF normalized_graduacao LIKE '%MŪKYŪ%' OR normalized_graduacao LIKE '%MUKYU%' OR normalized_graduacao LIKE '%MUKYU%' OR normalized_graduacao LIKE '%BRANCA%' THEN
    SELECT id INTO resolved_id FROM public.kyu_dan WHERE kyu_dan = 'mūkyū' LIMIT 1;
  ELSIF normalized_graduacao LIKE '%10%' OR normalized_graduacao LIKE '%CINZA%' THEN
    SELECT id INTO resolved_id FROM public.kyu_dan WHERE kyu_dan = '10º kyū' LIMIT 1;
  ELSIF normalized_graduacao LIKE '%8%' OR normalized_graduacao LIKE '%AZUL%' THEN
    SELECT id INTO resolved_id FROM public.kyu_dan WHERE kyu_dan = '8º kyū' LIMIT 1;
  ELSIF normalized_graduacao LIKE '%6%' OR normalized_graduacao LIKE '%AMARELA%' THEN
    SELECT id INTO resolved_id FROM public.kyu_dan WHERE kyu_dan = '6º kyū' LIMIT 1;
  ELSIF normalized_graduacao LIKE '%4%' OR normalized_graduacao LIKE '%LARANJA%' THEN
    SELECT id INTO resolved_id FROM public.kyu_dan WHERE kyu_dan = '4º kyū' LIMIT 1;
  ELSIF normalized_graduacao LIKE '%3%' OR normalized_graduacao LIKE '%VERDE%' THEN
    SELECT id INTO resolved_id FROM public.kyu_dan WHERE kyu_dan = '3º kyū' LIMIT 1;
  ELSIF normalized_graduacao LIKE '%2%' OR normalized_graduacao LIKE '%ROXA%' THEN
    SELECT id INTO resolved_id FROM public.kyu_dan WHERE kyu_dan = '2º kyū' LIMIT 1;
  ELSIF normalized_graduacao LIKE '%1%' OR normalized_graduacao LIKE '%MARROM%' THEN
    SELECT id INTO resolved_id FROM public.kyu_dan WHERE kyu_dan = '1º kyū' LIMIT 1;
  ELSIF normalized_graduacao LIKE '%PRETA%' OR normalized_graduacao LIKE '%YUDANSHA%' THEN
    SELECT id INTO resolved_id FROM public.kyu_dan WHERE kyu_dan = '1º dan' LIMIT 1;
  END IF;

  RETURN resolved_id;
END;
$$;

DO $$
BEGIN
  IF to_regclass('public.user_fed_lrsj') IS NOT NULL THEN
    ALTER TABLE public.user_fed_lrsj
      ADD COLUMN IF NOT EXISTS kyu_dan_id BIGINT REFERENCES public.kyu_dan(id);

    CREATE INDEX IF NOT EXISTS idx_user_fed_lrsj_kyu_dan_id ON public.user_fed_lrsj (kyu_dan_id);

    UPDATE public.user_fed_lrsj
    SET kyu_dan_id = public.resolve_kyu_dan_id(
      graduacao,
      NULLIF(regexp_replace(COALESCE(dan::TEXT, ''), '[^0-9]', '', 'g'), '')::INT,
      NULL
    )
    WHERE kyu_dan_id IS NULL;

    CREATE OR REPLACE FUNCTION public.set_user_fed_lrsj_kyu_dan_id()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    AS $fn$
    BEGIN
      NEW.kyu_dan_id := public.resolve_kyu_dan_id(
        NEW.graduacao,
        NULLIF(regexp_replace(COALESCE(NEW.dan::TEXT, ''), '[^0-9]', '', 'g'), '')::INT,
        NULL
      );

      IF NEW.graduacao IS NOT NULL AND trim(NEW.graduacao) <> '' AND NEW.kyu_dan_id IS NULL THEN
        RAISE EXCEPTION 'Graduação inválida: %, cadastre em public.kyu_dan antes de salvar.', NEW.graduacao;
      END IF;

      RETURN NEW;
    END;
    $fn$;

    DROP TRIGGER IF EXISTS trg_user_fed_lrsj_set_kyu_dan_id ON public.user_fed_lrsj;

    CREATE TRIGGER trg_user_fed_lrsj_set_kyu_dan_id
    BEFORE INSERT OR UPDATE OF graduacao, dan ON public.user_fed_lrsj
    FOR EACH ROW
    EXECUTE FUNCTION public.set_user_fed_lrsj_kyu_dan_id();
  END IF;
END;
$$;

DO $$
BEGIN
  IF to_regclass('public.atletas') IS NOT NULL THEN
    ALTER TABLE public.atletas
      ADD COLUMN IF NOT EXISTS kyu_dan_id BIGINT REFERENCES public.kyu_dan(id);

    CREATE INDEX IF NOT EXISTS idx_atletas_kyu_dan_id ON public.atletas (kyu_dan_id);

    UPDATE public.atletas
    SET kyu_dan_id = public.resolve_kyu_dan_id(graduacao, NULL, dan_nivel)
    WHERE kyu_dan_id IS NULL;

    CREATE OR REPLACE FUNCTION public.set_atletas_kyu_dan_id()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    AS $fn$
    BEGIN
      NEW.kyu_dan_id := public.resolve_kyu_dan_id(NEW.graduacao, NULL, NEW.dan_nivel);

      IF NEW.graduacao IS NOT NULL AND trim(NEW.graduacao) <> '' AND NEW.kyu_dan_id IS NULL THEN
        RAISE EXCEPTION 'Graduação inválida: %, cadastre em public.kyu_dan antes de salvar.', NEW.graduacao;
      END IF;

      RETURN NEW;
    END;
    $fn$;

    DROP TRIGGER IF EXISTS trg_atletas_set_kyu_dan_id ON public.atletas;

    CREATE TRIGGER trg_atletas_set_kyu_dan_id
    BEFORE INSERT OR UPDATE OF graduacao, dan_nivel ON public.atletas
    FOR EACH ROW
    EXECUTE FUNCTION public.set_atletas_kyu_dan_id();
  END IF;
END;
$$;

COMMENT ON TABLE public.kyu_dan IS 'Tabela mestre de graduações kyu/dan. Referência oficial para graduações no sistema.';

DO $$
BEGIN
  IF to_regclass('public.user_fed_lrsj') IS NOT NULL THEN
    COMMENT ON COLUMN public.user_fed_lrsj.kyu_dan_id IS 'FK para graduação oficial em public.kyu_dan';
  END IF;

  IF to_regclass('public.atletas') IS NOT NULL THEN
    COMMENT ON COLUMN public.atletas.kyu_dan_id IS 'FK para graduação oficial em public.kyu_dan';
  END IF;
END;
$$;
